# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: 'postgres'
  password: 'root'
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: point_check_app_development
  schema_search_path: public
  
test:
  <<: *default
  host: localhost
  database: point_check_app_test
  schema_search_path: public

production:
  <<: *default
  database: point_check_app_production
  username: point_check_app
  password: <%= ENV['POINT_CHECK_APP_DATABASE_PASSWORD'] %>
